### ISSUE TITLE
Security: lack of documentation. How to use a self-signed certificate made by yourself?

### ISSUE THREAD

**Issue by GitMAGI** [atc-net/atc-opc-ua#11]
Hi everybody. I think I'm missing something, because even if i make a self-signed certificate by myself (a der public and a pfx private), the client is still creating its own certificate. I really need to force the using of my certificate because the server will be able to trust only one client certificate which will be used by a scalable multi instance client process.
There is way to force the client taking a self-made certificate instead of creating its own?
Thank you.
Leonardo

**Comment by perkops** [comment]
Hi @GitMAGI,

Thank you for your question.

There should be a section in the readme, covering your situation: https://github.com/atc-net/atc-opc-ua?tab=readme-ov-file#configuring-opc-ua-security-settings

Using the OpcUaSecurityOptions you should be able to configure all necessary settings:

```json
{
  "OpcUaSecurityOptions": {
    "PkiRootPath": "opc/pki",
    "ApplicationCertificate": {
      "StoreType": "Directory",
      "StorePath": "own",
      "SubjectName": "CN=YourApp"
    },
    "RejectedCertificates": {
      "StoreType": "Directory",
      "StorePath": "rejected"
    },
    "TrustedIssuerCertificates": {
      "StoreType": "Directory",
      "StorePath": "issuers"
    },
    "TrustedPeerCertificates": {
      "StoreType": "Directory",
      "StorePath": "trusted"
    },
    "AddAppCertToTrustedStore": true,
    "AutoAcceptUntrustedCertificates": false,
    "MinimumCertificateKeySize": 1024,
    "RejectSha1SignedCertificates": true,
    "RejectUnknownRevocationStatus": true
  }
}
```

If you cannot use any appsettings to configure the ApplicationCertificate / SubjectName, you could also wire it up in code like this,

```csharp
  var opcUaSecurityOptions = new OpcUaSecurityOptions
  {
      PkiRootPath = "locationtomycertificate",
      ApplicationCertificate =
      {
          SubjectName = "my-custom-certificate-subject-name",
      },
  };

  services.AddTransient<IOpcUaClient, OpcUaClient>(s =>
  {
      var loggerFactory = s.GetRequiredService<ILoggerFactory>();
      return new OpcUaClient(
          loggerFactory.CreateLogger<OpcUaClient>(),
          new OptionsWrapper<OpcUaSecurityOptions>(opcUaSecurityOptions));
  });
```

Let me know if you experience other issues and feel free to reply with your specific code aswell.

**Comment by GitMAGI** [comment]
Hi, thanks for your reply.
I'm really sorry to bother you but I'm struggling here. 
I made a huge step forward: my certificate is taken into account by the Atc.Opc Client.

**Although I'm getting this exception**
```
Message: 
Test method <my-app-name>.Sending_UnitTest.Test_Security threw exception: 
Opc.Ua.ServiceResultException: Cannot access certificate private key. Subject=CN=<my-app-name>

Stack Trace: 
ApplicationInstance.CheckApplicationInstanceCertificate(Boolean silent, UInt16 minimumKeySize, UInt16 lifeTimeInMonths)
OpcUaClient.BuildAndValidateOpcUaApplicationAsync() line 250
OpcUaClient.ctor(ILogger`1 logger, IOptions`1 opcUaSecurityOptions) line 28
Sending_UnitTest.Test_Security() line 237
ThreadOperations.ExecuteWithAbortSafety(Action action)
```

**This is the code side**
```
[TestMethod]
public async Task Test_Security()
{
    await Task.Delay(1);

    string server_url = "opc.tcp://<local-machine>:62640/IntegrationObjects/ServerSimulator";

    string certPath = "Certificates";
    string certCN = "<my-app-name>";

    var options = new OptionsWrapper<OpcUaSecurityOptions>(new OpcUaSecurityOptions()
    {                
        PkiRootPath = certPath,
        RejectSha1SignedCertificates = true,
        AddAppCertToTrustedStore = false,
        AutoAcceptUntrustedCertificates = true,
        ApplicationCertificate = new CertificateInfo() { SubjectName = certCN, StorePath = "own", StoreType = "Directory" }
    });

    var client = new OpcUaClient(_loggerFactory.CreateLogger<OpcUaClient>(), options); // Where the exception occurs
....
```


**This is how I created the certificate (I'm on windows using openssl)**
**Set Application Name**
`set app_name=<my-app-name>`
**Create Public crt and Private key (without csr)**
`openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -keyout %app_name%.key -out %app_name%.crt -nodes -subj /CN=%app_name%`
**Create der format of the Public Certificate only**
`openssl base64 -d -in %app_name%.crt -out own\certs\%app_name%.der`
**Create pfx format of the Private Key only**
`openssl pkcs12 -export -inkey %app_name%.key -nocerts -passout pass: -out own\private\%app_name%.pfx`

_NOTE: I'm not using \<my-app-name\> as application name and CN, but I'm using an actual application name_

**Comment by GitMAGI** [comment]
@perkops **everything works fine**. My problem was just a matter of client certificate!
The certificate (self-signed) must be created with the rights properties and the .pfx file must contain both public cert and the private key.

These are the steps for creating the certificate:
- Set Application Name
set app_name=UT_GeneralPurpose
- Create Public crt and Private key
openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes -keyout %app_name%.key -out %app_name%.crt -config %app_name%.conf
- Create der format of the Public Certificate only
openssl x509 -inform PEM -outform DER -in %app_name%.crt -out own\certs\%app_name%.der
- Create pfx format of the Certificate and the Private Key
openssl pkcs12 -in %app_name%.crt -inkey %app_name%.key -passout pass: -export -out own\private\%app_name%.pfx

This is the openssl config file containing all the mandatory properties (%app_name%.conf)
```
[req]
distinguished_name = req_distinguished_name
prompt = no
x509_extensions = x509_extensions

[req_distinguished_name]
CN = <your-app-name>

[x509_extensions]
basicConstraints = CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid, issuer:always
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment, keyCertSign
extendedKeyUsage = TLS Web Server Authentication, TLS Web Client Authentication
subjectAltName = @alternate_names

[alternate_names]
URI.1 = urn:<your-machine-name>:<your-app-name>
DNS.1 = <your-machine-name>
```

**Comment by GitMAGI** [comment]
@perkops **everything works fine**. My problem was just a matter of client certificate!
The certificate (self-signed) must be created with the rights properties and the .pfx file must contain both public cert and the private key.

These are the steps for creating the certificate:
- Set Application Name
`set app_name=<your-app-name>`
- Create Public crt and Private key
`openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes -keyout %app_name%.key -out %app_name%.crt -config %app_name%.conf`
- Create der format of the Public Certificate only
`openssl x509 -inform PEM -outform DER -in %app_name%.crt -out own\certs\%app_name%.der`
- Create pfx format of the Certificate and the Private Key
`openssl pkcs12 -in %app_name%.crt -inkey %app_name%.key -passout pass: -export -out own\private\%app_name%.pfx`

This is the openssl config file containing all the mandatory properties (%app_name%.conf)
```
[req]
distinguished_name = req_distinguished_name
prompt = no
x509_extensions = x509_extensions

[req_distinguished_name]
CN = <your-app-name>

[x509_extensions]
basicConstraints = CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid, issuer:always
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment, keyCertSign
extendedKeyUsage = TLS Web Server Authentication, TLS Web Client Authentication
subjectAltName = @alternate_names

[alternate_names]
URI.1 = urn:<your-machine-name>:<your-app-name>
DNS.1 = <your-machine-name>
```
